parameters:
    virhi_pagination.subscriber.pagination.class: Virhi\Bundle\PaginationBundle\Pagination\EventSubscriber\PaginationEventSubscriber
    virhi_pagination.resolver.pagination.class: Virhi\Bundle\PaginationBundle\Pagination\HeaderResolver\PaginationHeaderResolver
    virhi_pagination.factory.fixedpagination.class: Virhi\Bundle\PaginationBundle\Factory\FixedPaginationFactory
    virhi_pagination.factory.pagination.class: Virhi\Bundle\PaginationBundle\Factory\PaginationFactory
    virhi_pagination.factory.range_pagination.class: Virhi\Bundle\PaginationBundle\Factory\RangeAdvancePaginationFactory

services:
    virhi_pagination.factory.pagination:
        class: %virhi_pagination.factory.pagination.class%
        arguments: [@router]

    virhi_pagination.factory.fixedpagination:
        class: %virhi_pagination.factory.fixedpagination.class%
        parent: virhi_pagination.factory.pagination

    virhi_pagination.factory.range_pagination:
        class: %virhi_pagination.factory.range_pagination.class%
        parent: virhi_pagination.factory.fixedpagination